server:
  port: 8088
  undertow:
    buffer-size: 1024

spring:
  profiles:
    active: dev
  application:
    name: simple-demo
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    dynamic:
      druid:
        initial-size: 100
        min-idle: 100
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 40
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 默认的数据源
      primary: master
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.8.203:3306/operator-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Mysql@13a
        # 从库数据源
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.8.203:3306/operator-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: readonly
          password: 123456!
  data:
    redis:
      timeout: 3000ms
      password: root123
#      password: cluster13a
#      cluster:
#        # 获取失败 最大重定向次数
#        max-redirects: 3
#        nodes:
#          - 192.168.8.203:6981
#          - 192.168.8.203:6982
#          - 192.168.8.203:6983
#          - 192.168.8.203:6984
#          - 192.168.8.203:6985
#          - 192.168.8.203:6986
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 200
          # 连接池中的最大空闲连接
          max-idle: 50
          #连接池中的最小空闲连接
          min-idle: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1

# http://localhost:8088/swagger-ui/index.html#/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: simple-demo
        url: /v3/api-docs

thinker:
  cloud:
    db:
      # 数据库类型
      type: mysql
      # 开启租户隔离
      tenant:
        enable: true
      # 开启数据权限
      data-scope:
        enable: true
    redis:
      # 开启延迟队列
      delayQueue:
        enabled: false

logging:
  level:
    root: info
