server:
  port: 8088
  undertow:
    buffer-size: 1024

spring:
  profiles:
    active: dev
  application:
    name: simple-demo
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    dynamic:
      druid:
        initial-size: 100
        min-idle: 100
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 40
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 默认的数据源
      primary: master
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.8.203:3306/operator-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456!
        # 从库数据源
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.8.203:3306/operator-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: readonly
          password: 123456!
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root123

# http://localhost:8088/swagger-ui/index.html#/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: simple-demo
        url: /v3/api-docs

thinker:
  cloud:
    redis:
      delayQueue:
        enabled: true

logging:
  level:
    root: info
